// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_info.proto

package com.pekall.pctool.protos;

public final class AppInfoProtos {
  private AppInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppInfoPOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string label = 1;
    boolean hasLabel();
    String getLabel();
    
    // required string package_name = 2;
    boolean hasPackageName();
    String getPackageName();
    
    // required string version_name = 3;
    boolean hasVersionName();
    String getVersionName();
    
    // required int32 version_code = 4;
    boolean hasVersionCode();
    int getVersionCode();
    
    // required bytes icon = 5;
    boolean hasIcon();
    com.google.protobuf.ByteString getIcon();
    
    // required int64 apk_file_size = 6;
    boolean hasApkFileSize();
    long getApkFileSize();
    
    // required string apk_file_path = 7;
    boolean hasApkFilePath();
    String getApkFilePath();
  }
  public static final class AppInfoP extends
      com.google.protobuf.GeneratedMessage
      implements AppInfoPOrBuilder {
    // Use AppInfoP.newBuilder() to construct.
    private AppInfoP(Builder builder) {
      super(builder);
    }
    private AppInfoP(boolean noInit) {}
    
    private static final AppInfoP defaultInstance;
    public static AppInfoP getDefaultInstance() {
      return defaultInstance;
    }
    
    public AppInfoP getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoP_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoP_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string label = 1;
    public static final int LABEL_FIELD_NUMBER = 1;
    private java.lang.Object label_;
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          label_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string package_name = 2;
    public static final int PACKAGE_NAME_FIELD_NUMBER = 2;
    private java.lang.Object packageName_;
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          packageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string version_name = 3;
    public static final int VERSION_NAME_FIELD_NUMBER = 3;
    private java.lang.Object versionName_;
    public boolean hasVersionName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getVersionName() {
      java.lang.Object ref = versionName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          versionName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getVersionNameBytes() {
      java.lang.Object ref = versionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        versionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 version_code = 4;
    public static final int VERSION_CODE_FIELD_NUMBER = 4;
    private int versionCode_;
    public boolean hasVersionCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getVersionCode() {
      return versionCode_;
    }
    
    // required bytes icon = 5;
    public static final int ICON_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString icon_;
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getIcon() {
      return icon_;
    }
    
    // required int64 apk_file_size = 6;
    public static final int APK_FILE_SIZE_FIELD_NUMBER = 6;
    private long apkFileSize_;
    public boolean hasApkFileSize() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getApkFileSize() {
      return apkFileSize_;
    }
    
    // required string apk_file_path = 7;
    public static final int APK_FILE_PATH_FIELD_NUMBER = 7;
    private java.lang.Object apkFilePath_;
    public boolean hasApkFilePath() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getApkFilePath() {
      java.lang.Object ref = apkFilePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          apkFilePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getApkFilePathBytes() {
      java.lang.Object ref = apkFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        apkFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      label_ = "";
      packageName_ = "";
      versionName_ = "";
      versionCode_ = 0;
      icon_ = com.google.protobuf.ByteString.EMPTY;
      apkFileSize_ = 0L;
      apkFilePath_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLabel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPackageName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersionName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersionCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasApkFileSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasApkFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLabelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, versionCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, icon_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, apkFileSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getApkFilePathBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLabelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPackageNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVersionNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, versionCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, icon_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, apkFileSize_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getApkFilePathBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pekall.pctool.protos.AppInfoProtos.AppInfoP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoP_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoP_fieldAccessorTable;
      }
      
      // Construct using com.pekall.pctool.protos.AppInfoProtos.AppInfoP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        packageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        versionName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        versionCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        icon_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        apkFileSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        apkFilePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pekall.pctool.protos.AppInfoProtos.AppInfoP.getDescriptor();
      }
      
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP getDefaultInstanceForType() {
        return com.pekall.pctool.protos.AppInfoProtos.AppInfoP.getDefaultInstance();
      }
      
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP build() {
        com.pekall.pctool.protos.AppInfoProtos.AppInfoP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pekall.pctool.protos.AppInfoProtos.AppInfoP buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pekall.pctool.protos.AppInfoProtos.AppInfoP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP buildPartial() {
        com.pekall.pctool.protos.AppInfoProtos.AppInfoP result = new com.pekall.pctool.protos.AppInfoProtos.AppInfoP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packageName_ = packageName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.versionName_ = versionName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.versionCode_ = versionCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.icon_ = icon_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.apkFileSize_ = apkFileSize_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.apkFilePath_ = apkFilePath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pekall.pctool.protos.AppInfoProtos.AppInfoP) {
          return mergeFrom((com.pekall.pctool.protos.AppInfoProtos.AppInfoP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pekall.pctool.protos.AppInfoProtos.AppInfoP other) {
        if (other == com.pekall.pctool.protos.AppInfoProtos.AppInfoP.getDefaultInstance()) return this;
        if (other.hasLabel()) {
          setLabel(other.getLabel());
        }
        if (other.hasPackageName()) {
          setPackageName(other.getPackageName());
        }
        if (other.hasVersionName()) {
          setVersionName(other.getVersionName());
        }
        if (other.hasVersionCode()) {
          setVersionCode(other.getVersionCode());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        if (other.hasApkFileSize()) {
          setApkFileSize(other.getApkFileSize());
        }
        if (other.hasApkFilePath()) {
          setApkFilePath(other.getApkFilePath());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLabel()) {
          
          return false;
        }
        if (!hasPackageName()) {
          
          return false;
        }
        if (!hasVersionName()) {
          
          return false;
        }
        if (!hasVersionCode()) {
          
          return false;
        }
        if (!hasIcon()) {
          
          return false;
        }
        if (!hasApkFileSize()) {
          
          return false;
        }
        if (!hasApkFilePath()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              label_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              packageName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              versionName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              versionCode_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              icon_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              apkFileSize_ = input.readInt64();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              apkFilePath_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string label = 1;
      private java.lang.Object label_ = "";
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        label_ = value;
        onChanged();
        return this;
      }
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      void setLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        label_ = value;
        onChanged();
      }
      
      // required string package_name = 2;
      private java.lang.Object packageName_ = "";
      public boolean hasPackageName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          packageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPackageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        packageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPackageName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      void setPackageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        packageName_ = value;
        onChanged();
      }
      
      // required string version_name = 3;
      private java.lang.Object versionName_ = "";
      public boolean hasVersionName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getVersionName() {
        java.lang.Object ref = versionName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          versionName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setVersionName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        versionName_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersionName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        versionName_ = getDefaultInstance().getVersionName();
        onChanged();
        return this;
      }
      void setVersionName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        versionName_ = value;
        onChanged();
      }
      
      // required int32 version_code = 4;
      private int versionCode_ ;
      public boolean hasVersionCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getVersionCode() {
        return versionCode_;
      }
      public Builder setVersionCode(int value) {
        bitField0_ |= 0x00000008;
        versionCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersionCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        versionCode_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes icon = 5;
      private com.google.protobuf.ByteString icon_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getIcon() {
        return icon_;
      }
      public Builder setIcon(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        icon_ = value;
        onChanged();
        return this;
      }
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000010);
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      
      // required int64 apk_file_size = 6;
      private long apkFileSize_ ;
      public boolean hasApkFileSize() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getApkFileSize() {
        return apkFileSize_;
      }
      public Builder setApkFileSize(long value) {
        bitField0_ |= 0x00000020;
        apkFileSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearApkFileSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        apkFileSize_ = 0L;
        onChanged();
        return this;
      }
      
      // required string apk_file_path = 7;
      private java.lang.Object apkFilePath_ = "";
      public boolean hasApkFilePath() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getApkFilePath() {
        java.lang.Object ref = apkFilePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          apkFilePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setApkFilePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        apkFilePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearApkFilePath() {
        bitField0_ = (bitField0_ & ~0x00000040);
        apkFilePath_ = getDefaultInstance().getApkFilePath();
        onChanged();
        return this;
      }
      void setApkFilePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        apkFilePath_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.pekall.pctool.protos.AppInfoP)
    }
    
    static {
      defaultInstance = new AppInfoP(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pekall.pctool.protos.AppInfoP)
  }
  
  public interface AppInfoPListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.pekall.pctool.protos.AppInfoP app_infos = 1;
    java.util.List<com.pekall.pctool.protos.AppInfoProtos.AppInfoP> 
        getAppInfosList();
    com.pekall.pctool.protos.AppInfoProtos.AppInfoP getAppInfos(int index);
    int getAppInfosCount();
    java.util.List<? extends com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder> 
        getAppInfosOrBuilderList();
    com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder getAppInfosOrBuilder(
        int index);
  }
  public static final class AppInfoPList extends
      com.google.protobuf.GeneratedMessage
      implements AppInfoPListOrBuilder {
    // Use AppInfoPList.newBuilder() to construct.
    private AppInfoPList(Builder builder) {
      super(builder);
    }
    private AppInfoPList(boolean noInit) {}
    
    private static final AppInfoPList defaultInstance;
    public static AppInfoPList getDefaultInstance() {
      return defaultInstance;
    }
    
    public AppInfoPList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoPList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoPList_fieldAccessorTable;
    }
    
    // repeated .com.pekall.pctool.protos.AppInfoP app_infos = 1;
    public static final int APP_INFOS_FIELD_NUMBER = 1;
    private java.util.List<com.pekall.pctool.protos.AppInfoProtos.AppInfoP> appInfos_;
    public java.util.List<com.pekall.pctool.protos.AppInfoProtos.AppInfoP> getAppInfosList() {
      return appInfos_;
    }
    public java.util.List<? extends com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder> 
        getAppInfosOrBuilderList() {
      return appInfos_;
    }
    public int getAppInfosCount() {
      return appInfos_.size();
    }
    public com.pekall.pctool.protos.AppInfoProtos.AppInfoP getAppInfos(int index) {
      return appInfos_.get(index);
    }
    public com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder getAppInfosOrBuilder(
        int index) {
      return appInfos_.get(index);
    }
    
    private void initFields() {
      appInfos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getAppInfosCount(); i++) {
        if (!getAppInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < appInfos_.size(); i++) {
        output.writeMessage(1, appInfos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < appInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appInfos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pekall.pctool.protos.AppInfoProtos.AppInfoPList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pekall.pctool.protos.AppInfoProtos.AppInfoPList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pekall.pctool.protos.AppInfoProtos.AppInfoPListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoPList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pekall.pctool.protos.AppInfoProtos.internal_static_com_pekall_pctool_protos_AppInfoPList_fieldAccessorTable;
      }
      
      // Construct using com.pekall.pctool.protos.AppInfoProtos.AppInfoPList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (appInfosBuilder_ == null) {
          appInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appInfosBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pekall.pctool.protos.AppInfoProtos.AppInfoPList.getDescriptor();
      }
      
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoPList getDefaultInstanceForType() {
        return com.pekall.pctool.protos.AppInfoProtos.AppInfoPList.getDefaultInstance();
      }
      
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoPList build() {
        com.pekall.pctool.protos.AppInfoProtos.AppInfoPList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pekall.pctool.protos.AppInfoProtos.AppInfoPList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pekall.pctool.protos.AppInfoProtos.AppInfoPList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoPList buildPartial() {
        com.pekall.pctool.protos.AppInfoProtos.AppInfoPList result = new com.pekall.pctool.protos.AppInfoProtos.AppInfoPList(this);
        int from_bitField0_ = bitField0_;
        if (appInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            appInfos_ = java.util.Collections.unmodifiableList(appInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.appInfos_ = appInfos_;
        } else {
          result.appInfos_ = appInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pekall.pctool.protos.AppInfoProtos.AppInfoPList) {
          return mergeFrom((com.pekall.pctool.protos.AppInfoProtos.AppInfoPList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pekall.pctool.protos.AppInfoProtos.AppInfoPList other) {
        if (other == com.pekall.pctool.protos.AppInfoProtos.AppInfoPList.getDefaultInstance()) return this;
        if (appInfosBuilder_ == null) {
          if (!other.appInfos_.isEmpty()) {
            if (appInfos_.isEmpty()) {
              appInfos_ = other.appInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppInfosIsMutable();
              appInfos_.addAll(other.appInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.appInfos_.isEmpty()) {
            if (appInfosBuilder_.isEmpty()) {
              appInfosBuilder_.dispose();
              appInfosBuilder_ = null;
              appInfos_ = other.appInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appInfosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAppInfosFieldBuilder() : null;
            } else {
              appInfosBuilder_.addAllMessages(other.appInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getAppInfosCount(); i++) {
          if (!getAppInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder subBuilder = com.pekall.pctool.protos.AppInfoProtos.AppInfoP.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAppInfos(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.pekall.pctool.protos.AppInfoP app_infos = 1;
      private java.util.List<com.pekall.pctool.protos.AppInfoProtos.AppInfoP> appInfos_ =
        java.util.Collections.emptyList();
      private void ensureAppInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          appInfos_ = new java.util.ArrayList<com.pekall.pctool.protos.AppInfoProtos.AppInfoP>(appInfos_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pekall.pctool.protos.AppInfoProtos.AppInfoP, com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder, com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder> appInfosBuilder_;
      
      public java.util.List<com.pekall.pctool.protos.AppInfoProtos.AppInfoP> getAppInfosList() {
        if (appInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appInfos_);
        } else {
          return appInfosBuilder_.getMessageList();
        }
      }
      public int getAppInfosCount() {
        if (appInfosBuilder_ == null) {
          return appInfos_.size();
        } else {
          return appInfosBuilder_.getCount();
        }
      }
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP getAppInfos(int index) {
        if (appInfosBuilder_ == null) {
          return appInfos_.get(index);
        } else {
          return appInfosBuilder_.getMessage(index);
        }
      }
      public Builder setAppInfos(
          int index, com.pekall.pctool.protos.AppInfoProtos.AppInfoP value) {
        if (appInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppInfosIsMutable();
          appInfos_.set(index, value);
          onChanged();
        } else {
          appInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAppInfos(
          int index, com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder builderForValue) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          appInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAppInfos(com.pekall.pctool.protos.AppInfoProtos.AppInfoP value) {
        if (appInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppInfosIsMutable();
          appInfos_.add(value);
          onChanged();
        } else {
          appInfosBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAppInfos(
          int index, com.pekall.pctool.protos.AppInfoProtos.AppInfoP value) {
        if (appInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppInfosIsMutable();
          appInfos_.add(index, value);
          onChanged();
        } else {
          appInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAppInfos(
          com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder builderForValue) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.add(builderForValue.build());
          onChanged();
        } else {
          appInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAppInfos(
          int index, com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder builderForValue) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          appInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAppInfos(
          java.lang.Iterable<? extends com.pekall.pctool.protos.AppInfoProtos.AppInfoP> values) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          super.addAll(values, appInfos_);
          onChanged();
        } else {
          appInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAppInfos() {
        if (appInfosBuilder_ == null) {
          appInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appInfosBuilder_.clear();
        }
        return this;
      }
      public Builder removeAppInfos(int index) {
        if (appInfosBuilder_ == null) {
          ensureAppInfosIsMutable();
          appInfos_.remove(index);
          onChanged();
        } else {
          appInfosBuilder_.remove(index);
        }
        return this;
      }
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder getAppInfosBuilder(
          int index) {
        return getAppInfosFieldBuilder().getBuilder(index);
      }
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder getAppInfosOrBuilder(
          int index) {
        if (appInfosBuilder_ == null) {
          return appInfos_.get(index);  } else {
          return appInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder> 
           getAppInfosOrBuilderList() {
        if (appInfosBuilder_ != null) {
          return appInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appInfos_);
        }
      }
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder addAppInfosBuilder() {
        return getAppInfosFieldBuilder().addBuilder(
            com.pekall.pctool.protos.AppInfoProtos.AppInfoP.getDefaultInstance());
      }
      public com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder addAppInfosBuilder(
          int index) {
        return getAppInfosFieldBuilder().addBuilder(
            index, com.pekall.pctool.protos.AppInfoProtos.AppInfoP.getDefaultInstance());
      }
      public java.util.List<com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder> 
           getAppInfosBuilderList() {
        return getAppInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pekall.pctool.protos.AppInfoProtos.AppInfoP, com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder, com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder> 
          getAppInfosFieldBuilder() {
        if (appInfosBuilder_ == null) {
          appInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pekall.pctool.protos.AppInfoProtos.AppInfoP, com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder, com.pekall.pctool.protos.AppInfoProtos.AppInfoPOrBuilder>(
                  appInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          appInfos_ = null;
        }
        return appInfosBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.pekall.pctool.protos.AppInfoPList)
    }
    
    static {
      defaultInstance = new AppInfoPList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pekall.pctool.protos.AppInfoPList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pekall_pctool_protos_AppInfoP_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pekall_pctool_protos_AppInfoP_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pekall_pctool_protos_AppInfoPList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pekall_pctool_protos_AppInfoPList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016app_info.proto\022\030com.pekall.pctool.prot" +
      "os\"\227\001\n\010AppInfoP\022\r\n\005label\030\001 \002(\t\022\024\n\014packag" +
      "e_name\030\002 \002(\t\022\024\n\014version_name\030\003 \002(\t\022\024\n\014ve" +
      "rsion_code\030\004 \002(\005\022\014\n\004icon\030\005 \002(\014\022\025\n\rapk_fi" +
      "le_size\030\006 \002(\003\022\025\n\rapk_file_path\030\007 \002(\t\"E\n\014" +
      "AppInfoPList\0225\n\tapp_infos\030\001 \003(\0132\".com.pe" +
      "kall.pctool.protos.AppInfoPB)\n\030com.pekal" +
      "l.pctool.protosB\rAppInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_pekall_pctool_protos_AppInfoP_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_pekall_pctool_protos_AppInfoP_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pekall_pctool_protos_AppInfoP_descriptor,
              new java.lang.String[] { "Label", "PackageName", "VersionName", "VersionCode", "Icon", "ApkFileSize", "ApkFilePath", },
              com.pekall.pctool.protos.AppInfoProtos.AppInfoP.class,
              com.pekall.pctool.protos.AppInfoProtos.AppInfoP.Builder.class);
          internal_static_com_pekall_pctool_protos_AppInfoPList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_pekall_pctool_protos_AppInfoPList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pekall_pctool_protos_AppInfoPList_descriptor,
              new java.lang.String[] { "AppInfos", },
              com.pekall.pctool.protos.AppInfoProtos.AppInfoPList.class,
              com.pekall.pctool.protos.AppInfoProtos.AppInfoPList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
